### ISSUE TITLE
This MIDI file won't load

### ISSUE THREAD

**Issue by Androphonomania** [wyskoj/midis2jam2#138]
**Describe the bug**
When I try and open this file in midis2jam2, it gives me an error that says "The MIDI file has bad data."

**Offending MIDI file**
[MIDI file that causes the bug](https://www.mediafire.com/file/yveua4zrckadoht/Battle%21_Deoxys.mid/file)

**Expected behavior**
It should load.

**Screenshots**
![image](https://user-images.githubusercontent.com/88868724/184472419-6b0f83d1-ab93-46d4-b134-4c73c1e0ef51.png)

**System**
Windows 11, RTX 2060, intel Core i7 9th Gen

**Additional context**
The error code is:
```
javax.sound.midi.InvalidMidiDataException: could not get sequence from file
	at java.desktop/javax.sound.midi.MidiSystem.getSequence(MidiSystem.java:829)
	at org.wysko.midis2jam2.starter.Execution$start$1$sequence$1.invokeSuspend(Execution.kt:100)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by wyskoj** [comment]
After peering into the hex dump of this file, I see that at offset 0x8CB, there is a meta message with a type of 0x91. This as an unsigned integer represents 145 which is outside the standard range of 0–127 for messages. This is causing that error to be thrown.

I don't know why that value is there, but I'm assuming it's because this is not a GM MIDI file. At the present time, midis2jam2 only fully supports GM MIDI files. 

#91 is open until I add support for XG, GS, etc.
