### ISSUE TITLE
Graphics library not being properly packaged for macOS

### ISSUE THREAD

**Issue by Ll3ma** [wyskoj/midis2jam2#203]
application launches but when i try to play a song i encounter this error. this is on an m1 macbook pro

java -jar /Applications/midis2jam2/midis2jam2-macosArm64-1.9.0.jar
11:27:48.843 I18n                      INFO   Locale file does not exist
11:27:48.845 I18n                      INFO   System locale is en, supported, using it
11:27:50.961 UpdateChecker             INFO   midis2jam2 is up to date.
A call to chooseDirectoryNative failed: null
Aug 26, 2024 11:27:56 AM com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.6.1-stable
 * Branch: HEAD
 * Git Hash: 4de10c3
 * Build Date: 2023-06-23
Exception in thread "jME3 Main" java.lang.UnsatisfiedLinkError: The required native library 'lwjgl' is not available for your OS: MacOSX_ARM64
	at com.jme3.system.NativeLibraryLoader.loadNativeLibrary(NativeLibraryLoader.java:538)
	at com.jme3.system.lwjgl.LwjglContext.loadNatives(LwjglContext.java:245)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:219)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by wyskoj** [comment]
@Ll3ma Re-open this issue if you still experience the problem with the latest version of the app.
