### ISSUE TITLE
midis2jam2 won't start

### ISSUE THREAD

**Issue by TheBlueRiolu** [wyskoj/midis2jam2#214]
**Describe the bug**
midis2jam2 does not get past the launcher when I hit play. It just freezes.

**Offending MIDI file**
Every MIDI file I have downloaded or made by hand does this. As of 9/9/24 I have 14 MIDI files.

**Expected behavior**
I expect midis2jam2 to run at all.

**System**
I am using a 13" MacBook Pro with Apple M1, 8 GB RAM, and macOS Ventura (13.2).

**Comment by TheBlueRiolu** [comment]
After updating Java and running from command line, I received this error:
```Sept 12, 2024 6:07:36 PM com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.6.1-stable
 * Branch: HEAD
 * Git Hash: 4de10c3
 * Build Date: 2023-06-23
Exception in thread "jME3 Main" java.lang.UnsatisfiedLinkError: The required native library 'lwjgl' is not available for your OS: MacOSX_ARM64
	at com.jme3.system.NativeLibraryLoader.loadNativeLibrary(NativeLibraryLoader.java:538)
	at com.jme3.system.lwjgl.LwjglContext.loadNatives(LwjglContext.java:245)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:219)
	at java.base/java.lang.Thread.run(Thread.java:1570)```

**Comment by wyskoj** [comment]
Watch #203 for updates.
