### ISSUE TITLE
Graphics environment sometimes fails to get display refresh rate

### ISSUE THREAD

**Issue by Coderdreams** [wyskoj/midis2jam2#233]
Picking a midi file and selecting a soundfont and trying to play it throws:

Exception in thread "DefaultDispatcher-worker-1" java.lang.ExceptionInInitializerError
        at org.wysko.midis2jam2.starter.Midis2jam2Application.execute(Execution.kt:154)
        at org.wysko.midis2jam2.starter.Execution$start$1.invokeSuspend(Execution.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4c407d3c, Dispatchers.Default]
Caused by: java.util.NoSuchElementException: Array is empty.
        at kotlin.collections.ArraysKt___ArraysKt.first(_Arrays.kt:1012)
        at org.wysko.midis2jam2.starter.ExecutionKt.<clinit>(Execution.kt:215)
        ... 8 more

**Offending MIDI file**

Agent orange midi from here: http://www.pimpfdm.com/DM-midi.html (I can't upload mid here)

**Expected behavior**
Playing of midi file

**System**
Ubuntu 24.04.1 LTS

/jbr/bin/java -version
openjdk version "17.0.11" 2024-04-16
OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
OpenJDK 64-Bit Server VM (build 17.0.11+0-17.0.11b1207.24-11852314, mixed mode)

midis2jam version:

https://github.com/wyskoj/midis2jam2/releases/download/v1.9.0/midis2jam2-linuxX64-1.9.0.jar

Using fluidsynth sf2 from:
/usr/share/sounds/sf2/FluidR3_GM.sf2
and
/usr/share/sounds/sf2/FluidR3_GS.sf2

**Comment by wyskoj** [comment]
Thanks for letting me know, I'll make sure this is fixed by the next version.

Note to self: https://github.com/wyskoj/midis2jam2/blob/a618e5af1ee4c6d4a11081ebac3104219134e458/src/main/kotlin/org/wysko/midis2jam2/starter/Execution.kt#L215

**Comment by Coderdreams** [comment]
Yes, I don't know why displayModes is empty in my Ubuntu install.
