### ISSUE TITLE
Execution error on Java 16 (OpenJDK)

### ISSUE THREAD

**Issue by parkerlreed** [wyskoj/midis2jam2#52]
**Describe the bug**
Crashes with assertion

```
[parker@wolfcola Downloads]$ java -jar midis2jam2-b08e1626.jar 
Jul 26, 2021 9:44:11 PM org.wysko.midis2jam2.GuiLauncher lambda$main$2
INFO: Checking for updates.
Exception in thread "Thread-0" java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:208)
        at org.wysko.midis2jam2.util.Utils.resourceToString(Utils.java:133)
        at org.wysko.midis2jam2.GuiLauncher.getVersion(GuiLauncher.java:194)
        at org.wysko.midis2jam2.GuiLauncher.lambda$main$2(GuiLauncher.java:144)
        at java.base/java.lang.Thread.run(Thread.java:831)
Jul 26, 2021 9:44:55 PM com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.4.0-stable
 * Branch: HEAD
 * Git Hash: cb5173b
 * Build Date: 2021-05-30
Inconsistency detected by ld.so: dl-lookup.c: 105: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
```

**Expected behavior**

I don't know, first time using it...

**System**
Arch Linux x86_64
openjdk 16

**Comment by parkerlreed** [comment]
That's with the latest build artifact.

When I try the 1.3.0 unix sh from releases I get this in the built-in error window

```
Uncaught exception thrown in Thread[jME3 Main,6,main]
NullPointerException: Cannot invoke "com.jme3.renderer.Renderer.invalidateState()" because "this.renderer" is null```

**Comment by wyskoj** [comment]
feaa908 should fix the assertion.

For the renderer exception, try enabling the "Legacy engine" checkbox in the launcher and see if it still errors.

**Comment by parkerlreed** [comment]
Just grabbed the latest build artifact. Still seems to be doing it (Tried with and without Legecy (Still need to try the legacy toggle on stable))

```
[parker@t495 Pictures]$ java -jar midis2jam2-feaa908d.jar 
Jul 27, 2021 1:59:51 PM org.wysko.midis2jam2.GuiLauncher lambda$main$2
INFO: Checking for updates.
Jul 27, 2021 1:59:52 PM org.wysko.midis2jam2.GuiLauncher lambda$main$2
INFO: Up to date.
Jul 27, 2021 2:00:28 PM com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.4.0-stable
 * Branch: HEAD
 * Git Hash: cb5173b
 * Build Date: 2021-05-30
Inconsistency detected by ld.so: dl-lookup.c: 105: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
```

**Comment by parkerlreed** [comment]
Just checked and the stable 1.3.0 doesn't have a toggle for Legacy

**Comment by parkerlreed** [comment]
Ok the stable 1.3.0 ~/midis2jam folder with the master build artifact WITH Legacy works. 

Legacy unchecked nets me (feas908 is copied in place of the 1.3.0 jar)

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jme3.util.ReflectionAllocator (file:/home/parker/midis2jam2/midis2jam2-1.3.0-all.jar) to method sun.nio.ch.DirectBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of com.jme3.util.ReflectionAllocator
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "jME3 Main"
AL lib: (EE) alc_cleanup: 1 device not closed
```

**Comment by wyskoj** [comment]
Java 16 might be giving you some issues, try running with Java 15 and see what happens.
