### ISSUE TITLE
Crash on launch on some OSs

### ISSUE THREAD

**Issue by dark279** [wyskoj/midis2jam2#56]
**Describe the bug**
I was trying to use both engines, and kept seeing:
```
Uncaught exception thrown in Thread[jME3 Main,6,main]
IllegalMonitorStateException: current thread is not owner
```
**Offending MIDI file**
Upload the MIDI file that causes the bug here.
(Unable to upload mid files)
**Expected behavior**
I was just expecting my short song to play.
**Screenshots**

**System**
Provide your OS, and computer specs if applicable.
 Ubuntu 14.04.6 LTS x86_64, nearly 4GB RAM,
CPU: Intel Core 2 Duo E8400 (2) @ 3.
GPU: Intel OptiPlex 755  
**Additional context**

**Comment by wyskoj** [comment]
Did you try enabling the "Legacy engine" checkbox, then starting?

**Comment by dark279** [comment]
yeah, still didn't work

**Comment by wyskoj** [comment]
Okay. It's unfortunate that this error is caused by many different reasons and isn't very descriptive, so it's hard to say exactly what the error is. I think it usually has to deal with a graphics engine bug. But if you can run the program from the terminal and copy the stack trace of the error that will help.

**Comment by dark279** [comment]
running the jar file results in:
```Exception in thread "main" java.lang.UnsupportedClassVersionError: org/wysko/midis2jam2/gui/GuiLauncher : Unsupported major.minor version 59.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:443)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:65)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:349)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:348)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482```

**Comment by wyskoj** [comment]
Yikes, a native method. I'll have to spend some time digging into this then.

**Comment by wyskoj** [comment]
That's probably the case. I've only tested the program on Windows 10, Windows 11, and Ubuntu 20.04 so it's likely that your OS can't initialize the engine.
